"""
프로젝트 전역 상수 정의
"""

# STATE 정의
STATE_OFF = 0
STATE_STANDBY = 1
STATE_ENABLE = 2
STATE_ERROR = 3

# Node IDs
NODE_ID_ALL = 0x00
NODE_ID_CM = 0x10
NODE_ID_LH = 0x20
NODE_ID_RH = 0x30
NODE_ID_LK = 0x40
NODE_ID_RK = 0x50
NODE_ID_LA = 0x60
NODE_ID_RA = 0x70

# TASK IDs
TASK_ID_LOWLEVEL = 0x00
TASK_ID_MIDLEVEL = 0x01
TASK_ID_MSG = 0x02
TASK_ID_WIDM = 0x03
TASK_ID_SYSMNGT = 0x04
TASK_ID_EXTDEV = 0x05

# SDO 상태
SDO_IDLE = 2
SDO_REQU = 1
SDO_SUCC = 0
SDO_FAIL = 255

# MSG SDO IDs
SDO_ID_MSG_SET_STATE = 0x01
SDO_ID_MSG_SET_ROUTINE = 0x03
SDO_ID_MSG_PDO_LIST = 0x04
SDO_ID_MSG_GUI_COMM_ONOFF = 0x06
SDO_ID_MSG_GUI_COMM_COMMAND = 0x07

# LOWLEVEL SDO IDs
SDO_ID_LOWLEVEL_GET_STATE = 0x00
SDO_ID_LOWLEVEL_SET_STATE = 0x01
SDO_ID_LOWLEVEL_GET_ROUTINE = 0x02
SDO_ID_LOWLEVEL_SET_ROUTINE = 0x03

# MIDLEVEL SDO IDs
SDO_ID_MIDLEVEL_GET_STATE = 0x00
SDO_ID_MIDLEVEL_SET_STATE = 0x01
SDO_ID_MIDLEVEL_GET_ROUTINE = 0x02
SDO_ID_MIDLEVEL_SET_ROUTINE = 0x03
SDO_ID_MIDLEVEL_POSITION_PERIODIC_SIG_INFO = 0x0D
SDO_ID_MIDLEVEL_POSITION_CTRL_P_GAIN = 0x18
SDO_ID_MIDLEVEL_POSITION_CTRL_D_GAIN = 0x19
SDO_ID_MIDLEVEL_MID_CTRL_SATURATION = 0x1A
SDO_ID_MIDLEVEL_SYSTEM_ID_SBS_INFO = 0x2C
SDO_ID_MIDLEVEL_POSITION_TANH_INFO = 0x4E
SDO_ID_MIDLEVEL_ANKLE_REF_INFO = 0x4F
SDO_ID_MIDLEVEL_ANKLE_REF_INFO2 = 0x50
SDO_ID_MIDLEVEL_ASSIST_ONOFF = 0x51
SDO_ID_MIDLEVEL_RISK_PARAM = 0x52
SDO_ID_MIDLEVEL_INIT_TORQUE = 0x53
SDO_ID_MIDLEVEL_PHASE_SHIFT = 0x54
SDO_ID_MIDLEVEL_ANKLE_REF_INFO3 = 0x55
SDO_ID_MIDLEVEL_IMPEDANCECTRL_INFO = 0x56
SDO_ID_MIDLEVEL_PROPORTIONALCTRL_INFO = 0x57
SDO_ID_MIDLEVEL_CALIBRATION_PARAMS_PART1 = 0x58
SDO_ID_MIDLEVEL_CALIBRATION_PARAMS_PART2 = 0x59

# WIDM PDO IDs
PDO_ID_WIDM_GAIT_PHASE = 0x0F

# LOWLEVEL PDO IDs
PDO_ID_LOWLEVEL_MID_ID_PROCESS_INPUT = 0x11
PDO_ID_LOWLEVEL_CURRENT_OUTPUT = 0x0C

# MIDLEVEL PDO IDs
PDO_ID_MIDLEVEL_LOOP_CNT = 0x00
PDO_ID_MIDLEVEL_REF_POSITION = 0x01
PDO_ID_MIDLEVEL_REF_VELOCITY = 0x02
PDO_ID_MIDLEVEL_ACTUAL_POSITION = 0x03
PDO_ID_MIDLEVEL_ACTUAL_VELOCITY_RAW = 0x04
PDO_ID_MIDLEVEL_SYSTEM_ID_SBS_FREQ = 0x05
PDO_ID_MIDLEVEL_IMP_CTRL_INPUT = 0x06
PDO_ID_MIDLEVEL_POS_PID_CTRL_INPUT = 0x07
PDO_ID_MIDLEVEL_VEL_PID_CTRL_INPUT = 0x08
PDO_ID_MIDLEVEL_VSD_INPUT = 0x09
PDO_ID_MIDLEVEL_UNIT_TRAJECTORY_BUFF_COUNT = 0x0A

PDO_ID_MIDLEVEL_ABSENCODER1_POSITION = 0x0C
PDO_ID_MIDLEVEL_ABSENCODER2_POSITION = 0x0D
PDO_ID_MIDLEVEL_DOB_DISTURABNCE = 0x0E
PDO_ID_MIDLEVEL_DOB_INPUT = 0x0F
PDO_ID_MIDLEVEL_FF_INPUT = 0x10
PDO_ID_MIDLEVEL_VELOCITY_ESTIMATED = 0x11
PDO_ID_MIDLEVEL_IMP_EPSILON = 0x12
PDO_ID_MIDLEVEL_IMP_KP = 0x13
PDO_ID_MIDLEVEL_IMP_KD = 0x14
PDO_ID_MIDLEVEL_IMP_LAMDA = 0x15
PDO_ID_MIDLEVEL_REF_POSITION1 = 0x16
PDO_ID_MIDLEVEL_REF_POSITION2 = 0x17
PDO_ID_MIDLEVEL_RISK = 0x18
PDO_ID_MIDLEVEL_TOTAL_REF_POSITION = 0x19
PDO_ID_MIDLEVEL_TVCF_VER_FREQUENCY = 0x1A
PDO_ID_MIDLEVEL_TRAPE_ID_DONE = 0x1B
PDO_ID_MIDLEVEL_SBS_ID_DONE = 0x1C
PDO_ID_MIDLEVEL_LS_CTRL_INPUT = 0x1D
PDO_ID_MIDLEVEL_LOADCELL_FORCE = 0x1E
PDO_ID_MIDLEVEL_REF_IMPEDANCE = 0x1F
PDO_ID_MIDLEVEL_GAMMA = 0x20
PDO_ID_MIDLEVEL_LOADCELL_TORQUE = 0x21

PDO_ID_MIDLEVEL_PMMG1 = 0x22
PDO_ID_MIDLEVEL_PMMG2 = 0x23
PDO_ID_MIDLEVEL_PMMG3 = 0x24
PDO_ID_MIDLEVEL_PMMG4 = 0x0B

# MSG Routine IDs
ROUTINE_ID_MSG_PDO_SEND = 0x00

# LOWLEVEL Routine IDs
ROUTINE_ID_LOWLEVEL_CURRENT_CTRL = 0x03
ROUTINE_ID_LOWLEVEL_ADV_FRICTION_COMPENSATION = 0x06

# MIDLEVEL Routine IDs
ROUTINE_ID_MIDLEVEL_SYS_ID_SBS = 0x00
ROUTINE_ID_MIDLEVEL_POSITION_SINE_REF = 0x04
ROUTINE_ID_MIDLEVEL_POSITION_CTRL = 0x05
ROUTINE_ID_MIDLEVEL_VELOCITY_CTRL = 0x06
ROUTINE_ID_MIDLEVEL_DISTURBANCE_OBS = 0x12
ROUTINE_ID_MIDLEVEL_FEEDFORWARD_FILTER = 0x15
ROUTINE_ID_MIDLEVEL_LINEARIZE_STIFFNESS = 0x18
ROUTINE_ID_MIDLEVEL_POSITION_TANH_REF = 0x19
ROUTINE_ID_MIDLEVEL_ANKLE_REF = 0x1A
ROUTINE_ID_MIDLEVEL_RISK_MANAGEMENT = 0x1B
ROUTINE_ID_MIDLEVEL_ANKLE_REF_PERIODIC = 0x1D
ROUTINE_ID_MIDLEVEL_ANKLE_COMPENSATOR = 0x1E
ROUTINE_ID_MIDLEVEL_PROPORTIONAL_ASSIST = 0x1F

# CAN Message Function Codes
SDO = 0x200
PDO = 0x300
SDO_SEND = 0x02
PDO_SEND = 0x03

# System ID
MECH_SYS_ID_SBS_RAW_DATA = 0x14
